# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


commands:
  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            echo ${CIRCLE_WORKFLOW_ID:0:5}
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1


#KEY_PAIR : fingerprint : c8:56:17:ac:e8:f1:0e:f4:c7:26:0b:86:1b:58:10:14
  inventory:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run :
          name: Install AWS-CLI and 
          command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version #verify aws cli installation
      - run  :
            name: Get Instance IP - Ansible Inventory
            command : |
                echo "[all]" > /home/circleci/project/inventory
                aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> /home/circleci/project/inventory
      - persist_to_workspace:
            root: ~/
            paths: 
             - project/inventory

  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c8:56:17:ac:e8:f1:0e:f4:c7:26:0b:86:1b:58:10:14"] # You can get this ID in the section where you registered the SSH Key
      - install_ansible
      - run :
          name: Install AWS-CLI and 
          command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version #verify aws cli installation
      - attach_workspace:
            at: ~/ 
      - run:
          name: Configure server
          command: |
            pwd
            ls
            ansible-playbook -i /home/circleci/project/inventory main-remote.yml
      
      - run:
          name: delete stack
          command: |
            echo "ansible playbook failed"
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
          when: on_fail

# Exercise: Smoke Testing
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run :
          name: Install AWS-CLI and 
          command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version #verify aws cli installation
      - run : 
          name: install tarball
          command: |
              wget https://dl.winehq.org/wine/source/1.9/wine-1.9.19.tar.bz2
              tar xzvf wine-1.9.19.tar.bz2
              cd wine-1.9.19
              ./configure
              make
              make install
      - attach_workspace:
            at: ~/ 
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            result= "grep -m2 /home/circleci/project/inventory"
            echo $result 
            curl -s --head ${result}:3000
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi
      - destroy_environment
        

workflows:
  AWS_INFRA:
    jobs:
      - create_infrastructure
      - inventory:
          requires : [create_infrastructure]
      - configure_infrastructure:
          requires : [inventory]
      - smoke_test:
          requires : [configure_infrastructure]
